Per ticket #24 commented out all the checks usplash since we dont have pretty boot up gui. Should remove them once we are sure it doesn't bork anything

diff --git a/Pyramid/dist/lib/lsb/init-functions b/Pyramid/dist/lib/lsb/init-functions
--- a/Pyramid/dist/lib/lsb/init-functions
+++ b/Pyramid/dist/lib/lsb/init-functions
@@ -123,39 +123,38 @@ killproc () {
 }
 
 log_success_msg () {
-    if type usplash_write >/dev/null 2>&1; then
-        usplash_write "STATUS $*" || true
-    fi
+#    if type usplash_write >/dev/null 2>&1; then
+#        usplash_write "STATUS $*" || true
+#    fi
     echo " * $@"
 }
 
 log_failure_msg () {
-    if type usplash_write >/dev/null 2>&1; then
-        usplash_write "STATUS $*" || true
-    fi
-
-    TPUT=/usr/bin/tput
-    if [ -x $TPUT ] && $TPUT hpa 60 >/dev/null 2>&1; then
-        RED=`$TPUT setaf 1`
-        NORMAL=`$TPUT op`
-        echo " $RED*$NORMAL $@"
-    else
+#    if type usplash_write >/dev/null 2>&1; then
+#        usplash_write "STATUS $*" || true
+#    fi
+#
+#    if [ -x $TPUT ] && $TPUT hpa 60 >/dev/null 2>&1; then
+#        RED=`$TPUT setaf 1`
+#        NORMAL=`$TPUT op`
+#        echo " $RED*$NORMAL $@"
+#    else
         echo " * $@"
-    fi
+#    fi
 }
 
 log_warning_msg () {
-    if type usplash_write >/dev/null 2>&1; then
-        usplash_write "STATUS $*" || true
-    fi
-    TPUT=/usr/bin/tput
-    if [ -x $TPUT ] && $TPUT hpa 60 >/dev/null 2>&1; then
-        YELLOW=`$TPUT setaf 3`
-        NORMAL=`$TPUT op`
-        echo " $YELLOW*$NORMAL $@"
-    else
+#    if type usplash_write >/dev/null 2>&1; then
+#        usplash_write "STATUS $*" || true
+#    fi
+#    TPUT=/usr/bin/tput
+#    if [ -x $TPUT ] && $TPUT hpa 60 >/dev/null 2>&1; then
+#        YELLOW=`$TPUT setaf 3`
+#        NORMAL=`$TPUT op`
+#        echo " $YELLOW*$NORMAL $@"
+#    else
         echo " * $@"
-    fi
+#    fi
 }
 
 #
@@ -177,23 +176,23 @@ log_begin_msg () {
                 return 1
         fi
 
-        if type usplash_write >/dev/null 2>&1; then
-	    usplash_write "TEXT $*" || true
-        fi
+#        if type usplash_write >/dev/null 2>&1; then
+#	    usplash_write "TEXT $*" || true
+#        fi
 
 	# Only do the fancy stuff if we have an appropriate terminal
 	# and if /usr is already mounted
-	TPUT=/usr/bin/tput
-	EXPR=/usr/bin/expr
-	if [ -x $TPUT ] && [ -x $EXPR ] && \
-		$TPUT xenl >/dev/null 2>&1 && \
-		$TPUT hpa 60 >/dev/null 2>&1; then
-	    COLS=`$TPUT cols`
-	    if [ -n "$COLS" ]; then
-		 COL=`$EXPR $COLS - 7`
-	    else
-		 COL=73
-	    fi
+#	TPUT=/usr/bin/tput
+#	EXPR=/usr/bin/expr
+#	if [ -x $TPUT ] && [ -x $EXPR ] && \
+#		$TPUT xenl >/dev/null 2>&1 && \
+#		$TPUT hpa 60 >/dev/null 2>&1; then
+#	    COLS=`$TPUT cols`
+#	    if [ -n "$COLS" ]; then
+#		 COL=`$EXPR $COLS - 7`
+#	    else
+#		 COL=73
+#	    fi
 	    # We leave the cursor `hanging' about-to-wrap
 	    # (see terminfo(5) xenl, which is approximately right).
 	    # That way if the script prints anything then we will
@@ -205,16 +204,16 @@ log_begin_msg () {
 	    # when they succeed and we won't be able to reliably know
 	    # where the colourful asterisk ought to go.
 	    
-	    printf " * $*       "
+#	    printf " * $*       "
 	    # Enough trailing spaces for ` [fail]' to fit in; if the
 	    # message is too long it wraps here rather than later,
 	    # which is what we want.
-	    $TPUT hpa `$EXPR $COLS - 1`
-	    printf ' '
-        else
+#	    $TPUT hpa `$EXPR $COLS - 1`
+#	    printf ' '
+#        else
 	    echo " * $*"
 	    COL=''
-        fi
+#        fi
 }
 
 # int log_end_message (int exitstatus)
@@ -223,13 +222,13 @@ log_end_msg () {
     # If no arguments were passed, return
     [ -z "$1" ] && return 1
 
-    if type usplash_write >/dev/null 2>&1; then
-        if [ $1 -eq 0 ]; then
-            usplash_write "SUCCESS ok" || true
-        else
-            usplash_write "FAILURE failed" || true
-        fi
-    fi
+#    if type usplash_write >/dev/null 2>&1; then
+#        if [ $1 -eq 0 ]; then
+#            usplash_write "SUCCESS ok" || true
+#        else
+#            usplash_write "FAILURE failed" || true
+#        fi
+#    fi
 
     if [ "$COL" ]; then
         printf "\r"
